name: Update stats

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Получить файлы репозитория
        uses: actions/checkout@v4

      - name: Проверить stats.json
        run: |
          echo "Проверяем stats.json..."
          cat stats.json
          echo "Проверка завершена успешно."
